### ISSUE TITLE
Path the file getting saved

### ISSUE THREAD

**Issue by Akayeshmantha** [philnash/service-worker-background-fetch#1]
Hi @philnash 

I tried out the amazing demo in https://fan-hubcap.glitch.me/. When I start the download it starts but I didn't get any notification on the download complete as well as I can't find the file. Where is it getting saved?.

**Comment by philnash** [comment]
Hi @Akayeshmantha,

It appears that the demo there was not working because the browser implementation had updated!

I've changed the code on Glitch now, so it should be working again.

The file itself is not downloaded to your file system, but stored using the [Cache API](https://developer.mozilla.org/en-US/docs/Web/API/Cache). You can see the details of this by opening dev tools in Chrome, going to the Application tab and looking under Cache Storage. It should be in the "downloads" cache.

Hope this helps, you can see [the updated code in the Glitch project](https://glitch.com/edit/#!/fan-hubcap?path=views%2Fsw.js%3A16%3A54).

**Comment by philnash** [comment]
I should update this repo with the latest code. Re-opening.

**Comment by Akayeshmantha** [comment]
Hi @philnash  thanks alot I checked the code it works
